package uci

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
)

// Config represents a complete UCI configuration package (e.g., "wireless", "network").
type Config struct {
	Package  string
	Sections []Section
}

// Section represents a single UCI config section.
type Section struct {
	Type    string
	Name    string                 // Named section (e.g., "radio0") or empty for anonymous
	Index   int                    // Index for anonymous sections
	Options map[string]interface{} // values are string or []string (for list options)
}

// Regular expressions for parsing UCI show output.
var (
	// Matches: wireless.radio0=wifi-device (section name cannot contain dots)
	reSectionDecl = regexp.MustCompile(`^([^.]+)\.([^.=]+)=(.+)$`)
	// Matches: wireless.radio0.type='mac80211'  (option: pkg.section.key=value)
	reOptionValue = regexp.MustCompile(`^([^.]+)\.([^.]+)\.([^=]+)=(.+)$`)
	// Matches: wireless.@wifi-iface[0]=wifi-iface
	reAnonSection = regexp.MustCompile(`^@([^[]+)\[(\d+)\]$`)

	// For parsing UCI file format (config blocks)
	reConfigLine  = regexp.MustCompile(`^\s*config\s+(\S+)\s*(?:'([^']*)'|"([^"]*)"|(\S+))?\s*$`)
	reOptionLine  = regexp.MustCompile(`^\s*option\s+(\S+)\s+(?:'([^']*)'|"([^"]*)"|(\S+))\s*$`)
	reListLine    = regexp.MustCompile(`^\s*list\s+(\S+)\s+(?:'([^']*)'|"([^"]*)"|(\S+))\s*$`)
)

// ParseShow parses the output of `uci show <package>` into a Config struct.
// Input format:
//
//	wireless.radio0=wifi-device
//	wireless.radio0.type='mac80211'
//	wireless.radio0.channel='36'
//	wireless.default_radio0=wifi-iface
//	wireless.default_radio0.device='radio0'
func ParseShow(output string) (*Config, error) {
	cfg := &Config{
		Sections: []Section{},
	}

	sectionMap := make(map[string]*Section)
	sectionOrder := []string{}

	lines := strings.Split(strings.TrimSpace(output), "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Try section declaration: pkg.name=type
		if m := reSectionDecl.FindStringSubmatch(line); m != nil {
			pkg, name, stype := m[1], m[2], m[3]
			if cfg.Package == "" {
				cfg.Package = pkg
			}

			if _, exists := sectionMap[name]; !exists {
				section := &Section{
					Type:    stype,
					Name:    name,
					Options: make(map[string]interface{}),
				}

				// Handle anonymous sections: @wifi-iface[0]
				if am := reAnonSection.FindStringSubmatch(name); am != nil {
					section.Name = "" // anonymous
					fmt.Sscanf(am[2], "%d", &section.Index)
				}

				sectionMap[name] = section
				sectionOrder = append(sectionOrder, name)
			}
			continue
		}

		// Try option/list: pkg.section.key=value
		if m := reOptionValue.FindStringSubmatch(line); m != nil {
			_, sectionName, key, value := m[1], m[2], m[3], m[4]

			// Strip quotes from value
			value = unquoteUCI(value)

			section, exists := sectionMap[sectionName]
			if !exists {
				continue // orphan option, skip
			}

			// Check if this is a list item (value already exists)
			if existing, ok := section.Options[key]; ok {
				switch v := existing.(type) {
				case string:
					// Promote to list
					section.Options[key] = []string{v, value}
				case []string:
					section.Options[key] = append(v, value)
				}
			} else {
				section.Options[key] = value
			}
		}
	}

	// Build ordered sections
	for _, name := range sectionOrder {
		cfg.Sections = append(cfg.Sections, *sectionMap[name])
	}

	return cfg, nil
}

// ParseUCIFile parses a UCI configuration file content (as generated by OpenSoHo)
// into a Config struct.
// Input format:
//
//	config wifi-device 'radio0'
//	    option type 'mac80211'
//	    option channel '36'
//
//	config wifi-iface
//	    option device 'radio0'
//	    option ssid 'MyNetwork'
//	    list macfilter 'AA:BB:CC:DD:EE:FF'
func ParseUCIFile(content string) (*Config, error) {
	cfg := &Config{
		Sections: []Section{},
	}

	var currentSection *Section
	anonIndex := make(map[string]int) // Track anonymous section indices per type

	lines := strings.Split(content, "\n")
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}

		// Try config line
		if m := reConfigLine.FindStringSubmatch(trimmed); m != nil {
			// Save previous section
			if currentSection != nil {
				cfg.Sections = append(cfg.Sections, *currentSection)
			}

			stype := m[1]
			name := firstNonEmpty(m[2], m[3], m[4])

			currentSection = &Section{
				Type:    stype,
				Name:    name,
				Options: make(map[string]interface{}),
			}

			if name == "" {
				// Anonymous section
				currentSection.Index = anonIndex[stype]
				anonIndex[stype]++
			}

			continue
		}

		// Try option line
		if m := reOptionLine.FindStringSubmatch(trimmed); m != nil && currentSection != nil {
			key := m[1]
			value := firstNonEmpty(m[2], m[3], m[4])
			currentSection.Options[key] = value
			continue
		}

		// Try list line
		if m := reListLine.FindStringSubmatch(trimmed); m != nil && currentSection != nil {
			key := m[1]
			value := firstNonEmpty(m[2], m[3], m[4])

			if existing, ok := currentSection.Options[key]; ok {
				switch v := existing.(type) {
				case string:
					currentSection.Options[key] = []string{v, value}
				case []string:
					currentSection.Options[key] = append(v, value)
				}
			} else {
				currentSection.Options[key] = []string{value}
			}
			continue
		}
	}

	// Don't forget last section
	if currentSection != nil {
		cfg.Sections = append(cfg.Sections, *currentSection)
	}

	return cfg, nil
}

// FindSection finds a section by type and name, or nil if not found.
func (c *Config) FindSection(stype, name string) *Section {
	for i := range c.Sections {
		if c.Sections[i].Type == stype && c.Sections[i].Name == name {
			return &c.Sections[i]
		}
	}
	return nil
}

// GetOption returns a string option value from a Section, or empty string.
func (s *Section) GetOption(key string) string {
	if v, ok := s.Options[key]; ok {
		if str, ok := v.(string); ok {
			return str
		}
	}
	return ""
}

// GetList returns a list option value from a Section, or nil.
func (s *Section) GetList(key string) []string {
	if v, ok := s.Options[key]; ok {
		switch val := v.(type) {
		case []string:
			return val
		case string:
			return []string{val}
		}
	}
	return nil
}

// SortedOptionKeys returns the option keys in sorted order for deterministic output.
func (s *Section) SortedOptionKeys() []string {
	keys := make([]string, 0, len(s.Options))
	for k := range s.Options {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// --- helpers ---

func unquoteUCI(s string) string {
	if len(s) >= 2 {
		if (s[0] == '\'' && s[len(s)-1] == '\'') || (s[0] == '"' && s[len(s)-1] == '"') {
			return s[1 : len(s)-1]
		}
	}
	return s
}

func firstNonEmpty(vals ...string) string {
	for _, v := range vals {
		if v != "" {
			return v
		}
	}
	return ""
}
