package uci

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestParseShow_SimpleWireless(t *testing.T) {
	input := `wireless.radio0=wifi-device
wireless.radio0.type='mac80211'
wireless.radio0.channel='36'
wireless.radio0.htmode='VHT80'
wireless.radio0.band='5g'
wireless.default_radio0=wifi-iface
wireless.default_radio0.device='radio0'
wireless.default_radio0.network='lan'
wireless.default_radio0.mode='ap'
wireless.default_radio0.ssid='OpenWrt'
wireless.default_radio0.encryption='psk2'
wireless.default_radio0.key='secret123'`

	cfg, err := ParseShow(input)
	require.NoError(t, err)
	assert.Equal(t, "wireless", cfg.Package)
	assert.Equal(t, 2, len(cfg.Sections))

	// First section: radio0
	radio := cfg.Sections[0]
	assert.Equal(t, "wifi-device", radio.Type)
	assert.Equal(t, "radio0", radio.Name)
	assert.Equal(t, "mac80211", radio.GetOption("type"))
	assert.Equal(t, "36", radio.GetOption("channel"))
	assert.Equal(t, "VHT80", radio.GetOption("htmode"))

	// Second section: default_radio0
	iface := cfg.Sections[1]
	assert.Equal(t, "wifi-iface", iface.Type)
	assert.Equal(t, "default_radio0", iface.Name)
	assert.Equal(t, "radio0", iface.GetOption("device"))
	assert.Equal(t, "OpenWrt", iface.GetOption("ssid"))
}

func TestParseShow_WithLists(t *testing.T) {
	input := `network.br_lan=device
network.br_lan.type='bridge'
network.br_lan.name='br-lan'
network.br_lan.ports='lan1'
network.br_lan.ports='lan2'
network.br_lan.ports='lan3'`

	cfg, err := ParseShow(input)
	require.NoError(t, err)
	assert.Equal(t, 1, len(cfg.Sections))

	section := cfg.Sections[0]
	assert.Equal(t, "bridge", section.GetOption("type"))
	ports := section.GetList("ports")
	assert.Equal(t, []string{"lan1", "lan2", "lan3"}, ports)
}

func TestParseShow_AnonymousSections(t *testing.T) {
	input := `wireless.@wifi-iface[0]=wifi-iface
wireless.@wifi-iface[0].device='radio0'
wireless.@wifi-iface[0].ssid='Network1'
wireless.@wifi-iface[1]=wifi-iface
wireless.@wifi-iface[1].device='radio1'
wireless.@wifi-iface[1].ssid='Network2'`

	cfg, err := ParseShow(input)
	require.NoError(t, err)
	assert.Equal(t, 2, len(cfg.Sections))

	// Anonymous sections should have empty Name and correct Index
	assert.Equal(t, "", cfg.Sections[0].Name)
	assert.Equal(t, 0, cfg.Sections[0].Index)
	assert.Equal(t, "Network1", cfg.Sections[0].GetOption("ssid"))

	assert.Equal(t, "", cfg.Sections[1].Name)
	assert.Equal(t, 1, cfg.Sections[1].Index)
	assert.Equal(t, "Network2", cfg.Sections[1].GetOption("ssid"))
}

func TestParseShow_EmptyInput(t *testing.T) {
	cfg, err := ParseShow("")
	require.NoError(t, err)
	assert.Equal(t, 0, len(cfg.Sections))
}

func TestParseUCIFile_Wireless(t *testing.T) {
	input := `
config wifi-device 'radio0'
        option type 'mac80211'
        option channel '36'
        option htmode 'VHT80'

config wifi-iface 'default_radio0'
        option device 'radio0'
        option network 'lan'
        option mode 'ap'
        option ssid 'TestNetwork'
        option encryption 'sae-mixed'
        option key 'password123'
`

	cfg, err := ParseUCIFile(input)
	require.NoError(t, err)
	assert.Equal(t, 2, len(cfg.Sections))

	radio := cfg.Sections[0]
	assert.Equal(t, "wifi-device", radio.Type)
	assert.Equal(t, "radio0", radio.Name)
	assert.Equal(t, "mac80211", radio.GetOption("type"))
	assert.Equal(t, "36", radio.GetOption("channel"))

	iface := cfg.Sections[1]
	assert.Equal(t, "wifi-iface", iface.Type)
	assert.Equal(t, "default_radio0", iface.Name)
	assert.Equal(t, "TestNetwork", iface.GetOption("ssid"))
}

func TestParseUCIFile_WithLists(t *testing.T) {
	input := `
config device
        option type 'bridge'
        option name 'br-lan'
        list ports 'lan1'
        list ports 'lan2'
        list ports 'lan3'
`

	cfg, err := ParseUCIFile(input)
	require.NoError(t, err)
	assert.Equal(t, 1, len(cfg.Sections))

	section := cfg.Sections[0]
	assert.Equal(t, "device", section.Type)
	assert.Equal(t, "", section.Name) // anonymous
	ports := section.GetList("ports")
	assert.Equal(t, []string{"lan1", "lan2", "lan3"}, ports)
}

func TestParseUCIFile_AnonymousSections(t *testing.T) {
	input := `
config wifi-iface
        option device 'radio0'
        option ssid 'Guest'

config wifi-iface
        option device 'radio1'
        option ssid 'IoT'
`

	cfg, err := ParseUCIFile(input)
	require.NoError(t, err)
	assert.Equal(t, 2, len(cfg.Sections))
	assert.Equal(t, "", cfg.Sections[0].Name)
	assert.Equal(t, 0, cfg.Sections[0].Index)
	assert.Equal(t, "", cfg.Sections[1].Name)
	assert.Equal(t, 1, cfg.Sections[1].Index)
}

func TestParseUCIFile_OpenSoHoWirelessOutput(t *testing.T) {
	// Real output generated by OpenSoHo's generateWifiConfig
	input := `
config wifi-iface 'wifinet2'
        option device 'radio0'
        option mode 'ap'
        option ssid 'HomeNetwork'
        option encryption 'sae-mixed'
        option key 'MySecurePassword'
        option ieee80211r '1'
        option mobility_domain 'abcd'
        option ft_over_ds '0'
        option ft_psk_generate_local '1'

config wifi-iface 'wifinet3'
        option device 'radio1'
        option mode 'ap'
        option ssid 'HomeNetwork'
        option encryption 'sae-mixed'
        option key 'MySecurePassword'
        option ieee80211r '1'
        option mobility_domain 'abcd'
        option ft_over_ds '0'
        option ft_psk_generate_local '1'
`

	cfg, err := ParseUCIFile(input)
	require.NoError(t, err)
	assert.Equal(t, 2, len(cfg.Sections))

	// Check 802.11r config
	iface := cfg.Sections[0]
	assert.Equal(t, "wifinet2", iface.Name)
	assert.Equal(t, "HomeNetwork", iface.GetOption("ssid"))
	assert.Equal(t, "1", iface.GetOption("ieee80211r"))
	assert.Equal(t, "abcd", iface.GetOption("mobility_domain"))
}

func TestFindSection(t *testing.T) {
	cfg := &Config{
		Package: "wireless",
		Sections: []Section{
			{Type: "wifi-device", Name: "radio0", Options: map[string]interface{}{"channel": "36"}},
			{Type: "wifi-iface", Name: "wifinet0", Options: map[string]interface{}{"ssid": "Test"}},
		},
	}

	found := cfg.FindSection("wifi-device", "radio0")
	assert.NotNil(t, found)
	assert.Equal(t, "36", found.GetOption("channel"))

	notFound := cfg.FindSection("wifi-device", "radio99")
	assert.Nil(t, notFound)
}

func TestGetOption_Missing(t *testing.T) {
	s := Section{Options: map[string]interface{}{"key": "value"}}
	assert.Equal(t, "value", s.GetOption("key"))
	assert.Equal(t, "", s.GetOption("nonexistent"))
}

func TestGetList_FromString(t *testing.T) {
	s := Section{Options: map[string]interface{}{"single": "item"}}
	assert.Equal(t, []string{"item"}, s.GetList("single"))
}

func TestGetList_Missing(t *testing.T) {
	s := Section{Options: map[string]interface{}{}}
	assert.Nil(t, s.GetList("nonexistent"))
}
